import type {
  Product,
  Category,
  Banner,
  Promotion,
  Review,
  Testimonial,
} from "./types";

export const categories: Category[] = [
  {
    id: "1",
    name: "Phones and Tablets",
    slug: "phones-tablets",
    description: "Latest smartphones and tablets",
    image: "/electronics-category.png",
    icon: "📱",
    productCount: 85,
    subcategories: [
      {
        id: "1-1",
        name: "Smartphones",
        slug: "smartphones",
        description: "Latest smartphones",
        image: "/modern-smartphones.png",
      },
      {
        id: "1-2",
        name: "Tablets",
        slug: "tablets",
        description: "High-performance tablets",
        image: "/various-tablets.png",
      },
      {
        id: "1-3",
        name: "Accessories",
        slug: "phone-accessories",
        description: "Phone and tablet accessories",
        image: "/phone-accessories.png",
      },
    ],
  },
  {
    id: "2",
    name: "Computing",
    slug: "computing",
    description: "Laptops, desktops and computer accessories",
    image: "/electronics-category.png",
    icon: "💻",
    productCount: 67,
    subcategories: [
      {
        id: "2-1",
        name: "Laptops",
        slug: "laptops",
        description: "High-performance laptops",
        image: "/various-laptops.png",
      },
      {
        id: "2-2",
        name: "Desktops",
        slug: "desktops",
        description: "Desktop computers",
        image: "/desktop-computers.png",
      },
      {
        id: "2-3",
        name: "Computer Accessories",
        slug: "computer-accessories",
        description: "Keyboards, mice, monitors",
        image: "/computer-accessories.png",
      },
    ],
  },
  {
    id: "3",
    name: "Electronics",
    slug: "electronics",
    description: "Audio, gaming and electronic devices",
    image: "/electronics-category.png",
    icon: "🎧",
    productCount: 92,
    subcategories: [
      {
        id: "3-1",
        name: "Headphones",
        slug: "headphones",
        description: "Premium audio devices",
        image: "/diverse-people-listening-headphones.png",
      },
      {
        id: "3-2",
        name: "Gaming",
        slug: "gaming",
        description: "Gaming consoles and accessories",
        image: "/gaming-devices.png",
      },
      {
        id: "3-3",
        name: "Smart Home",
        slug: "smart-home",
        description: "Smart home devices",
        image: "/smart-home-devices.png",
      },
      {
        id: "3-4",
        name: "Accessories",
        slug: "accessories",
        description: "Assorted electronic accessories",
        image: "/smart-home-devices.png",
      },
    ],
  },
  {
    id: "4",
    name: "Fashion",
    slug: "fashion",
    description: "Trendy clothing and accessories",
    image: "/fashion-category.png",
    icon: "👗",
    productCount: 234,
    subcategories: [
      {
        id: "4-1",
        name: "Men's Clothing",
        slug: "mens-clothing",
        description: "Stylish men's wear",
        image: "/mens-clothing-display.png",
      },
      {
        id: "4-2",
        name: "Women's Clothing",
        slug: "womens-clothing",
        description: "Trendy women's fashion",
        image: "/womens-clothing.png",
      },
      {
        id: "4-3",
        name: "Accessories",
        slug: "accessories",
        description: "Fashion accessories",
        image: "/fashion-accessories-collection.png",
      },
    ],
  },
  {
    id: "5",
    name: "Home & Office",
    slug: "home-office",
    description: "Furniture and office supplies",
    image: "/home-office-category.jpg",
    icon: "🏠",
    productCount: 189,
    subcategories: [
      {
        id: "5-1",
        name: "Furniture",
        slug: "furniture",
        description: "Quality furniture pieces",
        image: "/assorted-living-room-furniture.png",
      },
      {
        id: "5-2",
        name: "Office Supplies",
        slug: "office-supplies",
        description: "Essential office items",
        image: "/assorted-office-supplies.png",
      },
      {
        id: "5-3",
        name: "Home Decor",
        slug: "home-decor",
        description: "Beautiful home decorations",
        image: "/cozy-living-room.png",
      },
    ],
  },
  {
    id: "6",
    name: "Health & Beauty",
    slug: "health-beauty",
    description: "Personal care and wellness products",
    image: "/health-beauty-category.jpg",
    icon: "💄",
    productCount: 145,
    subcategories: [
      {
        id: "6-1",
        name: "Skincare",
        slug: "skincare",
        description: "Premium skincare products",
        image: "/skincare-products-display.png",
      },
      {
        id: "6-2",
        name: "Makeup",
        slug: "makeup",
        description: "Quality makeup products",
        image: "/makeup-products-flatlay.png",
      },
      {
        id: "6-3",
        name: "Wellness",
        slug: "wellness",
        description: "Health and wellness items",
        image: "/wellness-products-still-life.png",
      },
    ],
  },
  {
    id: "7",
    name: "Sports & Outdoors",
    slug: "sports-outdoors",
    description: "Sports equipment and outdoor gear",
    image: "/sports-outdoors-category.jpg",
    icon: "⚽",
    productCount: 167,
    subcategories: [
      {
        id: "7-1",
        name: "Fitness Equipment",
        slug: "fitness-equipment",
        description: "Home fitness gear",
        image: "/diverse-fitness-equipment.png",
      },
      {
        id: "7-2",
        name: "Outdoor Gear",
        slug: "outdoor-gear",
        description: "Camping and hiking gear",
        image: "/assorted-outdoor-gear.png",
      },
      {
        id: "7-3",
        name: "Sports Apparel",
        slug: "sports-apparel",
        description: "Athletic clothing",
        image: "/diverse-sports-apparel.png",
      },
    ],
  },
  {
    id: "8",
    name: "Baby Products",
    slug: "baby-products",
    description: "Everything for your little ones",
    image: "/baby-products-category.jpg",
    icon: "👶",
    productCount: 98,
    subcategories: [
      {
        id: "8-1",
        name: "Baby Clothing",
        slug: "baby-clothing",
        description: "Comfortable baby clothes",
        image: "/baby-clothing.jpg",
      },
      {
        id: "8-2",
        name: "Baby Gear",
        slug: "baby-gear",
        description: "Essential baby equipment",
        image: "/baby-gear.jpg",
      },
      {
        id: "8-3",
        name: "Toys",
        slug: "toys",
        description: "Educational and fun toys",
        image: "/colorful-baby-toys.png",
      },
    ],
  },
];

export const products: Product[] = [
  {
    id: "1",
    name: "Samsung Galaxy Z Fold 6 Case With S Pen Holder & Stylus, Hard PC Shockproof Protective Cover For Galaxy Z Fold6 5G",
    description:
      "This case is only suitable for Samsung Galaxy Z Fold 6 and is not compatible with other models.",
    price: 550000,
    originalPrice: 850000,
    images: [
      "/phones_and_tablets/galaxyfold.jpg",
      "/phones_and_tablets/galaxyfold2.jpg",
      "/phones_and_tablets/galaxyfold3.jpg",
    ],
    category: "Phones and Tablets",
    subcategory: "Smartphones",
    brand: "Samsung",
    stock: 6,
    rating: 4.8,
    reviewCount: 342,
    featured: true,
    tags: ["smartphone", "samsung", "premium", "latest"],
    specifications: {
      SKU: "SA948EA3ICKJ1NAFAMZ",
      Weight: "0.03kg",
      Color: "Black",
      Main_Material: "Leather",
    },
    variations: [
      {
        id: "1-128",
        name: "Fold 5",
        price: 480000,
        originalPrice: 850000,
        stock: 5,
      },
      {
        id: "1-256",
        name: "Fold 6",
        price: 550000,
        originalPrice: 850000,
        stock: 2,
      },
    ],
    mainFeatures: [
      "100% fashionable and durable. Offering a sophisticated look and great feel.",
      ".Corner bumpers protection for drops. Soft materials offer maximum protection from bumps and hard-hits for the back and sides of your phone.",
      "All buttons and corners are elevated, and raised edges lift the screen and camera lens off the surface.",
      "Keep your phone in like-new condition well and preserves its looks and features, to protect your phone hurt from scratches and gives you mobile phone a special look.",
    ],
    keyFeatures: [
      "This case is only suitable for Samsung Galaxy Z Fold 6 and is not compatible with other models.",
      "Precise Cutouts: Wide cutouts and responsive press keys, as well as easy access to all ports, buttons, cameras, speakers, and mics.",
      "Stable & Durable – Raised beveled edge keeps your touchscreen safe, dust protection, scratch protection and drop protection.",
      "A comprehensive new upgraded anti-fall protective cover with novel and fashionable appearance.",
      "Keeps your device thin and form fitting to fit right in your pocket and bag. This fantastic cases gives your phone a fresh look, and it could be a perfect gift.",
    ],
    whatsInTheBox: ["Cover", "Pen"],
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-20T14:30:00Z",
  },
  {
    id: "2",
    name: "Samsung Tab A9 Folio Slim Lightweight Tablet Case",
    description: "Premium Android smartphone with S Pen and AI features",
    price: 145000,
    originalPrice: 250000,
    images: [
      "/phones_and_tablets/galaxycase.jpg",
      "/phones_and_tablets/galaxycase2.jpg",
      "/phones_and_tablets/galaxycase3.jpg",
    ],
    category: "Phones and Tablets",
    subcategory: "Accessories",
    brand: "Samsung",
    stock: 5,
    rating: 4.7,
    reviewCount: 289,
    featured: true,
    tags: ["smartphone", "samsung", "android", "phonecase"],
    specifications: {
      SKU: "SA948EA3P8WFQNAFAMZ",
      Weight: "0.05kg",
      Color: "Black",
    },
    variations: [
      {
        id: "7-256",
        name: "A7 Lite",
        price: 95000,
        originalPrice: 250000,
        stock: 10,
      },
      {
        id: "7-512",
        name: "A9",
        price: 145000,
        originalPrice: 250000,
        stock: 18,
      },
      {
        id: "7-1tb",
        name: "A9 Plus",
        price: 155000,
        originalPrice: 250000,
        stock: 2,
      },
    ],
    mainFeatures: [
      "Built-in smart cover auto on/auto sleep function.",
      "Compact, elegant, stylish, easy to install and remove.",
      "Convenient position for watching movies or writing.",
      "100% high quality, customized and fits your tablet perfectly.",
      "Against unwanted bumps, accidental drops, scratches, bruises or stains.",
      "Package includes one (1) protective case.",
    ],
    keyFeatures: ["Protective.", "Black.", "Flip.", "Both sides covered."],
    whatsInTheBox: ["Phone Case"],
    createdAt: "2024-01-12T09:30:00Z",
    updatedAt: "2024-01-22T11:15:00Z",
  },
  {
    id: "3",
    name: "Samsung Galaxy Z Fold 6 Case With Screen Guard",
    description:
      "Samsung Galaxy Z Fold 6 Case with S Pen Holder & Stylus, Hard PC Shockproof Protective Cover for Galaxy Z Fold6 5GCompatibility",
    price: 250000,
    originalPrice: 650000,
    images: ["/phones_and_tablets/galaxyfoldcase.jpg"],
    category: "Phones and Tablets",
    subcategory: "Accessories",
    brand: "Samsung",
    stock: 4,
    rating: 4.9,
    reviewCount: 156,
    featured: true,
    tags: ["case", "samsung", "professional"],
    specifications: {
      SKU: "SA948EA3ZJZWTNAFAMZ",
      Weight: "0.05kg",
      Certifications: "Eco Friendly",
      Camera: "Black",
      From_the_Manufacturer: "Durable and Protective",
      Warranty_Address: "Zebra Plaza",
    },
    variations: [
      {
        id: "8-128",
        name: "Fold 6",
        price: 250000,
        originalPrice: 650000,
        stock: 3,
      },
    ],
    mainFeatures: [
      "This case is only suitable for Samsung Galaxy Z Fold 6 and is not compatible with other models.",
      "Please Note: Please confirm your phone model before buying.",
      "Fashionabl and durable. Offering a sophisticated look and great feel.",
      "Keep your phone in like-new condition well and preserves its looks and features, to protect your phone hurt from scratches and gives you mobile phone a special look.",
    ],
    keyFeatures: [
      "This case is only suitable for Samsung Galaxy Z Fold 6 and is not compatible with other models.",
      "Precise Cutouts: Wide cutouts and responsive press keys, as well as easy access to all ports, buttons, cameras, speakers, and mics.",
      "Stable & Durable – Raised beveled edge keeps your touchscreen safe, dust protection, scratch protection and drop protection.",
      "A comprehensive new upgraded anti-fall protective cover with novel and fashionable appearance.",
      "Keeps your device thin and form fitting to fit right in your pocket and bag. This fantastic cases gives your phone a fresh look, and it could be a perfect gift.",
    ],
    whatsInTheBox: ["Cover", "Screen Guard"],
    createdAt: "2024-01-10T14:20:00Z",
    updatedAt: "2024-01-25T16:45:00Z",
  },
  {
    id: "4",
    name: "Defender Shock Proof for Galaxy Tab A9",
    description: "Defender Shock Proof for Galaxy Tab A9 / A9 Plus BLACK",
    price: 250000,
    originalPrice: 650000,
    images: [
      "/phones_and_tablets/galaxyshockproof.jpg",
      "/phones_and_tablets/galaxyshockproof2.jpg",
      "/phones_and_tablets/galaxyshockproof3.jpg",
    ],
    category: "Phones and Tablets",
    subcategory: "Accessories",
    brand: "Samsung",
    stock: 4,
    rating: 4.5,
    reviewCount: 78,
    featured: false,
    tags: ["case", "samsung", "protection"],
    specifications: {
      SKU: "GE779EA48AN87NAFAMZ",
      Weight: "350g",
      Color: "Black",
    },
    variations: [
      {
        id: "9-galaxyA9",
        name: "A9",
        price: 250000,
        originalPrice: 650000,
        stock: 3,
      },
      {
        id: "9-galaxyA9Plus",
        name: "A9 Plus",
        price: 350000,
        originalPrice: 650000,
        stock: 4,
      },
    ],
    mainFeatures: [
      "Defender provides protection for all Samsung tablets for more protection and 360 rotating angles.",
    ],
    keyFeatures: [
      "Shell Type: Hard",
      "Brand: Seymac",
      "Target Gender: Unisex",
      "Color: Black / Black",
      "Theme: Tablet Case",
      "Model Number: For Samsung Galaxy Tab A9+, A9",
    ],
    whatsInTheBox: ["Cover"],
    createdAt: "2024-01-08T11:00:00Z",
    updatedAt: "2024-01-20T13:30:00Z",
  },
  {
    id: "5",
    name: 'Samsung Galaxy A16 4G 6.7" 8GB RAM 256GB ROM 50MP 5000mAh - Black"',
    description: "Powerful laptop with M3 Pro chip for professional workflows",
    price: 950000,
    images: ["/phones_and_tablets/galaxya16.jpg"],
    category: "Phones and Tablets",
    subcategory: "Smartphones",
    brand: "Samsung",
    stock: 3,
    rating: 4.9,
    reviewCount: 128,
    featured: true,
    tags: ["galaxy", "samsung"],
    specifications: {
      SKU: "SA948MP3LS5BFNAFAMZ",
      Weight: "0.19kg",
      Color: "Black",
    },
    variations: [
      {
        id: "2-m3pro",
        name: "A15 256",
        price: 950000,
        stock: 3,
      },
    ],
    mainFeatures: [
      "Dive into your favourite content with the stunning clarity and vibrant colours of Galaxy A16 4G's FHD+ Super AMOLED display. The expansive 6.7-inch screen with minimised bezels brings every moment to life.",
      "Slimmed down to just 7.9mm in thickness, Galaxy A16 4G slips right into your hand, pocket and daily life. Available in Blue Black, Light Grey and Light Green, it combines elegant design with enhanced portability.",
      "Take high-quality shots of your everyday life with advanced camera features. Capture memories vividly with a 50MP Main Camera, take clear selfies with a 13MP Front Camera to make each moment shine.",
      "With the upgraded 2.4GHz CPU, you can power through your foes fast and stream your favorite show without missing a beat.",
      "Enjoy what you love without worrying about battery life—the 5,000mAh battery keeps Galaxy A16 4G running strong on a single charge. Plus with Super Fast Charging, it's back in action quickly.",
    ],
    keyFeatures: [
      "Network Technology: GSM / HSPA / LTE",
      "SIM: Hybrid Dual SIM (Nano-SIM, dual stand-by)",
      "Size: 6.7 inches, 110.2 cm2 (~86.0% screen-to-body ratio)",
      "Platform: OS Android 14, up to 6 major Android upgrades, One UI 6.1",
      "Internal: 256GB 8GB RAM",
      "Main Camera: Triple 50 MP",
      "Comms: WLAN Wi-Fi 802.11 a/b/g/n/ac, dual-band, Wi-Fi Direct",
      "Bluetooth: 5.3, A2DP, LE",
      "USB: USB Type-C 2.0",
      "Battery Type: 5000 mAh, non-removable",
    ],
    whatsInTheBox: ["Samsung Galaxy A16"],
    createdAt: "2024-01-10T09:00:00Z",
    updatedAt: "2024-01-18T16:45:00Z",
  },
  {
    id: "6",
    name: "Silicone Case For Samsung Galaxy S8 S9 S10 Plus",
    description:
      "Silicone Case For Samsung Galaxy S8 S9 S10 Plus S6 S7 Edge S4 S5 Neo Note 8 9 3 4 5 A3 A5 A7 2015 2016 2017 Luxury Phone Cover(Purple)",
    price: 45000,
    originalPrice: 87000,
    images: ["/phones_and_tablets/siliconecase.jpg"],
    category: "Phones and Tablets",
    subcategory: "Accessories",
    brand: "",
    stock: 22,
    rating: 4.6,
    reviewCount: 94,
    featured: false,
    tags: ["samsung", "silicon", "case"],
    specifications: {
      SKU: "GE779EA46SQYZNAFAMZ",
      Size: "10cm x 5cm x 1cm",
      Weight: "0.03kg",
    },
    variations: [
      {
        id: "10-i5",
        name: "Note 8",
        price: 87000,
        originalPrice: 87000,
        stock: 4,
      },
      {
        id: "10-i7",
        name: "Note 9",
        price: 87000,
        originalPrice: 87000,
        stock: 3,
      },
      {
        id: "10-s8-1tb",
        name: "S8 Plus",
        price: 87000,
        originalPrice: 87000,
        stock: 3,
      },
      {
        id: "10-i7-plus",
        name: "S9 Plus",
        price: 48000,
        originalPrice: 87000,
        stock: 3,
      },
      {
        id: "10-s10-1tb",
        name: "S10",
        price: 87000,
        originalPrice: 87000,
        stock: 3,
      },
      {
        id: "10-s10pl-1tb",
        name: "S10 Plus",
        price: 45000,
        originalPrice: 87000,
        stock: 3,
      },
    ],
    mainFeatures: [
      "Customer satisfaction is very important for us. If you are satisfied with the items you ordered, please leave 9833 stars feedback. If you are not satisfied with our products or service, please let us know and give us the opportunity to make things right. thank you.",
    ],
    keyFeatures: [
      "Retail Package:Yes",
      "Type:Fitted Case",
      "Function:Dirt-resistant, Anti-knock, Heavy Duty Protection",
      "Compatible Brand:Samsung",
      "Compatible Samsung Model:Galaxy Note4, I9500 GALAXY S IV, Galaxy S5, Galaxy S6, Galaxy S6 edge, GALAXY S6 EDGE PLUS, Note 5, Galaxy Note III, Galaxy S8, Galaxy S8 Plus, Galaxy S7, Galaxy S7 Edge, Galaxy Note 8, Galaxy S9, Galaxy Note 9",
      "Design:Sports, Business, Matte, Cute, Plain",
      "Size:S 6 7 S6edge S7edge S8Plus S9Plus Note8 Pink Black Purple blue Girl design",
      "Features:Origin Mobile accessory Housing Casing Coque Woman",
      "Material:Soft Silicone",
      "Quality:100% New Brand High Quality Durable Flexible Touch Bag shell funda",
      "Model 1:Fundas For Samsung galaxy G900 G920 G925 G930 G935 G950 G955",
      "Model 2:capa For Samsung galaxy G900f G920f G925f G930f G935f G950f G955f",
      "Model 3:cases For Samsung S 5 6 7 8 S5neo S6edge S7edge S8Plus",
      "Features:Fashion Magnetic holder Pretty High Quality bags fundas capa shells",
      "Colors:Red , Pink , Yellow , Purple , Black , Blue , Green , white",
    ],
    whatsInTheBox: [],
    createdAt: "2024-01-14T10:30:00Z",
    updatedAt: "2024-01-24T14:20:00Z",
  },
  {
    id: "7",
    name: "Samsung Wireless Super Fast Charging Powerbank",
    description: "Samsung Wireless Super Fast Charging Powerbank",
    price: 285000,
    originalPrice: 350000,
    images: [
      "/phones_and_tablets/samsungpowerbank.jpg",
      "/phones_and_tablets/samsungpowerbank2.jpg",
      "/phones_and_tablets/samsungpowerbank3.jpg",
      "/phones_and_tablets/samsungpowerbank4.jpg",
      "/phones_and_tablets/samsungpowerbank5.jpg",
    ],
    category: "Phones and Tablets",
    subcategory: "Accessories",
    brand: "Samsung",
    stock: 8,
    rating: 4.8,
    reviewCount: 67,
    featured: true,
    tags: ["powerbank", "samsung", "fastcharger"],
    specifications: {
      SKU: "SA948EA4RMX57NAFAMZ",
      Weight: "0.05kg",
      Color: "May Vary",
      Main_Material: "PvC",
      From_the_Manufacturer: "Keep away from heat or fire",
    },
    variations: [
      {
        id: "11-rtx4070",
        name: "3rtt",
        price: 285000,
        stock: 8,
      },
    ],
    mainFeatures: [
      "Samsung Wireless Portable Power Bank best price in Kenya. Recharge both wired and wireless devices with this 25W USB Type-C Wireless Portable Power Bank from Samsung. The power bank features two USB Type-C ports and a built-in Qi-compatible wireless charging pad. This gives you the ability to recharge up to three devices simultaneously, spanning a wide array of categories, such as wireless headphones, smartwatches, and smartphones.",
      "The battery can fast charge up to two wired devices at up to 25W, while the wireless pad provides up to 7.5W of power to Qi-compatible products. Four built-in LED status lights conveniently let you know how much power is left in the power bank. When it’s time to recharge the battery, it too can take advantage of up to 25W of fast charging.",
      "Take the convenience of wireless charging on the road. The new Wireless Battery Pack allows you to wirelessly charge your Galaxy S10e, S10, S10+ or Galaxy Watch Active, so you don’t have to worry even when there’s no outlet in sight.",
    ],
    keyFeatures: [
      "Brand: Samsung",
      "Capacity: 10,000000Amh",
      "Wireless Charging",
      "Usb cable",
      "Fast Charging",
    ],
    whatsInTheBox: ["Samsung wireless powerbank", "Cable"],
    createdAt: "2024-01-16T12:00:00Z",
    updatedAt: "2024-01-26T15:30:00Z",
  },
  {
    id: "8",
    name: "Tecno High Speed Portable 4G MIFI open to all All Networks",
    description:
      "Tecno MiFi 8 Users 150Mbps 4G Portable High Speed Wi-Fi Hotspot",
    price: 200000,
    originalPrice: 350000,
    images: [
      "/computing/mifi.jpg",
      "/computing/mifi2.jpg",
      "/computing/mifi3.jpg",
      "/computing/mifi4.jpg",
    ],
    category: "Computing",
    subcategory: "Computer Accessories",
    brand: "Tecno",
    stock: 9,
    rating: 4.7,
    reviewCount: 234,
    featured: true,
    tags: ["mifi", "4g", "wireless"],
    specifications: {
      SKU: "TE339EA45QM33NAFAMZ",
      Weight: "0.03kg",
      Color: "White, Black",
      Main_Material: "Plastic",
      Certifications: "Eco Friendly",
    },
    variations: [
      {
        id: "mifi-4g",
        name: "MiFi",
        price: 200000,
        stock: 9,
      },
    ],
    mainFeatures: [
      "The Tecno MiFi TR109C 4G LTE Portable Device provides a compact and high-speed solution. For wireless internet connectivity. Designed for portability and efficiency, this device delivers robust performance with support for 4G LTE networks. Wi-Fi speeds up to 150 Mbps, making it ideal for both personal and professional use.",
      "Key Features Tecno TR109C MiFi 8 Users 150Mbps 4G.",
      "4G LTE Connectivity: The TR109C supports 4G LTE networks, offering fast and reliable internet speeds. With its capability to reach speeds of up to 150 Mbps, the device ensures smooth browsing, streaming, and downloading. Up to 8 WiFi devices simultaneously including laptops, smartphones, tablets and smart TVs.",
      "Portable Design: Compact and lightweight, the TR109C is easy to carry, fitting conveniently in a pocket or bag.",
      "Single Band WiFi: The MiFi device operates on a single band (typically 2.4 GHz), providing stable and reliable WiFi connectivity for multiple devices. This setup allows users to share the internet with smartphones, tablets, laptops, and other gadgets.",
      "Multiple Device Connectivity: They can connect several devices simultaneously, allowing users to share their internet connection with family, friends, or colleagues. This feature is particularly useful for group settings or collaborative work environments.",
    ],
    keyFeatures: [
      "Item Height: 16 Millimeters",
      "Item Width: 6.1 Centimeters",
      "Product Dimensions: 9.7 x 6.1 x 1.6 cm; 110 Grams",
      "Batteries: 1 Lithium Polymer batteries required. (included)",
      "Item model number: TR109C",
      "Are Batteries Included: Yes",
      "Number of Lithium Ion Cells: 1",
      "Included Components Mifi: 1User Manual",
      "Item Weight: 110g",
    ],
    whatsInTheBox: [],
    createdAt: "2024-01-11T08:45:00Z",
    updatedAt: "2024-01-21T10:15:00Z",
  },
  {
    id: "9",
    name: "Lenovo Laptop Thinkpad X270 , X250 , X260, T440p, T440s , T450, Charger 20V 3.25A 65W USB Pin",
    description:
      "Lenovo Laptop Charger 20V 3.25A 65WCharge and power your laptop with this Laptop Charger",
    price: 98000,
    originalPrice: 450000,
    images: [
      "/computing/thinkpadcharger.jpg",
      "/computing/thinkpadcharger2.jpg",
      "/computing/thinkpadcharger3.jpg",
    ],
    category: "Computing",
    subcategory: "Computer Accessories",
    brand: "Lenovo",
    stock: 4,
    rating: 4.7,
    reviewCount: 256,
    featured: false,
    tags: ["charger", "thinkpad", "fastcharger"],
    specifications: {
      SKU: "LE842EA3R2FZCNAFAMZ",
      Weight: "0.4kg",
      Color: "Black",
    },
    variations: [
      {
        id: "2-std",
        name: "Type 1",
        price: 98000,
        stock: 2,
      },
      {
        id: "2-pro",
        name: "Type 2",
        price: 285000,
        stock: 2,
      },
    ],
    mainFeatures: [
      "This laptop power supply is engineered with enough power to deliver a strong charge to any compatible laptop. This unit gives you surge protection, over-current protection, voltage protection and over-temperature protection to keep your laptop operating and charging at the correct voltage.",
      "Built to safeguard your laptop against damage, this charger will not let you down. Order for this Laptop charger from Jumia Kenya and have it delivered at your doorstep.",
      "This unit gives you surge protection, over-current protection, voltage protection and over-temperature protection to keep your laptop operating and charging at the correct voltage. Built to safeguard your laptop against damage, this charger will not let you down.",
    ],
    keyFeatures: [
      "Surge protection",
      "Over-current protection",
      "Voltage protection",
      "Over-temperature protection",
    ],
    whatsInTheBox: ["Lenovo  Laptop Charger"],
    createdAt: "2024-01-12T11:30:00Z",
    updatedAt: "2024-01-22T13:15:00Z",
  },
  {
    id: "10",
    name: "Hp Mouse Dual Mode Rechargeable Bluetooth Wireless Silent Click",
    description:
      "Hp Mouse Dual Mode Rechargeable Bluetooth Wireless Silent Click - Black.",
    price: 98000,
    originalPrice: 280000,
    images: ["/computing/mouse.jpg", "/computing/mouse2.jpg"],
    category: "Computing",
    subcategory: "Computer Accessories",
    brand: "Hp",
    stock: 12,
    rating: 4.9,
    reviewCount: 445,
    featured: true,
    tags: ["mouse", "hp", "playstation", "next-gen"],
    specifications: {
      SKU: "HP246EA4WGFPWNAFAMZ",
      "Weight (kg)": "0.02",
      Storage: "825GB SSD",
      Color: "Black",
    },
    variations: [
      {
        id: "13-digital",
        name: "1",
        price: 98000,
        stock: 12,
      },
    ],
    mainFeatures: [
      "Get this amazing HP mouse with long lasting rechargeable mouse. Battery lasts for over 14 days and 30 days standby. Dual mode with bluetooth and wireless can work with macbooks, windows and smart tv including other devices.",
    ],
    keyFeatures: [
      "Dual Mode Mouse",
      "Silent",
      "Long Lasting Battery",
      "Bluetooth and Wireless Dongle",
    ],
    whatsInTheBox: [
      "Hp Rechargeable Mouse",
      "1 Charging Cable",
      "1 Usb Receiver",
    ],
    createdAt: "2024-01-09T16:20:00Z",
    updatedAt: "2024-01-19T18:45:00Z",
  },
  {
    id: "11",
    name: "Hp Envy X360 2-in-1 Laptop, Core 5 120U, 8GB RAM, 512GB SSD",
    description:
      "Hp Envy X360 2-in-1 Laptop, Core 5 120U, 8GB RAM, 512GB SSD, 14 FHD Touchscreen Display, Fingerprint Reader, Natural Silver (1YR WRTY)",
    price: 4850000,
    originalPrice: 8800000,
    images: [
      "/computing/hpenvy.jpg",
      "/computing/hpenvy2.jpg",
      "/computing/hpenvy3.jpg",
      "/computing/hpenvy4.jpg",
      "/computing/hpenvy5.jpg",
    ],
    category: "Computing",
    subcategory: "Laptops",
    brand: "Hp",
    stock: 6,
    rating: 4.4,
    reviewCount: 1234,
    featured: true,
    tags: ["hp", "envy", "laptops"],
    specifications: {
      SKU: "HP246CL3L06T0NAFAMZ",
      "Weight (kg)": "1.51",
      Color: "Silver",
    },
    variations: [
      {
        id: "14-white",
        name: "Envy",
        price: 4850000,
        stock: 6,
      },
    ],
    mainFeatures: [
      "The HP Envy x360 14 2-in-1 Laptop PC levels up your work or downtime in every possible way, with an enhanced responsive touchscreen, amazing audio, and advanced collaboration technology —all backed by a design with recycled materials, serious power, plus all the apps and security features you need for an unstoppable you.",
      "Built for the hustle",
      "With the touchscreen and the latest Intel® Processor, this laptop helps make all you do more powerful",
      "Privacy on lock",
      "This laptop layers built-in security with privacy features, like the manual camera shutter and Fingerprint reader",
      "Next-level screen time",
      "The FHD screen, HP Audio Boost, and 9-hour battery life keep you immersed in your favorite shows",
    ],
    keyFeatures: [
      "Display: 14 diagonal, FHD (1920 x 1080), multitouch-enabled, IPS, edge-to-edge glass, micro-edge, 300 nits, low power, 62.5% sRGB",
      "Processor: Intel® Core™ i5-1235U (up to 5.0 GHz with Intel® Turbo Boost Technology, 12 MB L3 cache, 10 cores, 12 threads)",
      "Memory: 8 GB DDR4-3200 MHz RAM (onboard)",
      "Storage: 512 GB PCIe® Gen4 NVMe™ M.2 SSD",
      "Operating System: Windows® 11 Home",
      "Features: Wi-Fi, Webcam, Bluetooth, Fingerprint Reader",
    ],
    whatsInTheBox: [
      "HP Envy x360 2-in-1 Laptop",
      "User Guide",
      "Charging Adapter",
    ],
    createdAt: "2024-01-13T09:15:00Z",
    updatedAt: "2024-01-23T11:30:00Z",
  },
  {
    id: "12",
    name: "Multimedia 2.0 Speaker",
    description: "Multimedia 2.0 Speaker For All - Black",
    price: 57000,
    originalPrice: 135000,
    images: ["/computing/speaker.jpg"],
    category: "Computing",
    subcategory: "Computer Accessories",
    brand: "",
    stock: 12,
    rating: 4.8,
    reviewCount: 892,
    featured: false,
    tags: ["speaker", "loud", "noise-canceling", "music"],
    specifications: {
      SKU: "GE779EA3I4XWONAFAMZ",
      "Weight (kg)": "0.057",
      Color: "Black",
    },
    variations: [],
    mainFeatures: [
      "Durable Plastic Cabinet:Crafted from sturdy plastic, these speakers withstand daily use and travel",
      "USB Powered Convenience:Effortlessly powered via USB, these speakers offer a hassle-free setup for your devices",
      "3.5mm Audio Interface:Connects seamlessly to a variety of devices with its standard 3.5mm audio port",
      "High Output Power:Delivers a powerful audio experience with its 6W output, enhancing your listening sessions",
      "Best Computer Speakers Budget-Connect Computer Speakers To Tv-Portable Design:Compact and lightweight, these speakers are perfect for on-the-go audio enjoyment",
    ],
    keyFeatures: [
      "Pure and elegant sound high-quality with unsurpassed effect",
      "Incompliance with acoustics and algorithm rationale",
      "Flexible sound with distinct tone levels",
      "Small sized design, easy to take",
    ],
    whatsInTheBox: ["2.0 Multimedia Speaker"],
    createdAt: "2024-01-07T14:45:00Z",
    updatedAt: "2024-01-17T16:20:00Z",
  },
  {
    id: "13",
    name: "Other Portable Gently Insert The Instant Bright Usb Light",
    description:
      "Other Portable Gently Insert The Instant Bright Usb Light - Pink",
    price: 15200,
    originalPrice: 28000,
    images: [
      "/computing/usblight.jpg",
      "/computing/usblight2.jpg",
      "/computing/usblight3.jpg",
    ],
    category: "Computing",
    subcategory: "Computer Accessories",
    brand: "Other",
    stock: 8,
    rating: 4.5,
    reviewCount: 89,
    featured: false,
    tags: ["light", "usb", "pink"],
    specifications: {
      SKU: "OT296EA4UD5ERNAFAMZ",
      "Product Line": "USB Lights for Laptop/Power bank",
      Model: "USB LED",
      "Weight (kg)": "0.01",
      Color: "Pink",
      "Main Material": "LED",
    },
    variations: [],
    mainFeatures: [
      "By using lowest work voltage: 5V safety and reliability and high efficiency",
      "USB Connection to any iBook, PowerBook, Cube, PC, NoteBook, PowerBank, Wall Charger",
      "Ultra bright with low power consumption without frequency change",
      "Plug and Play",
      "Powered by USB port, no external power needed",
      "Definitely essential gear for night work",
    ],
    keyFeatures: [
      "Equiped with 6 pcs LED lamp beads",
      "Light weight",
      "Portable",
      "Energy-efficiency",
      "Soft lighting to avoid eye fatigue",
    ],
    whatsInTheBox: ["1 Led light"],
    createdAt: "2024-01-08T14:20:00Z",
    updatedAt: "2024-01-19T10:30:00Z",
  },
  {
    id: "14",
    name: "Hp Elitebook 840 G3 , Adapter Charger Pin",
    description:
      "Hp Elitebook 840 G3 , Adapter Charger Pin - Complete With Power Cable -Black",
    price: 155000,
    originalPrice: 290000,
    images: ["/computing/adapter.jpg", "/computing/adapter2.jpg"],
    category: "Computing",
    subcategory: "Computer Accessories",
    brand: "Hp",
    stock: 6,
    rating: 4.6,
    reviewCount: 145,
    featured: true,
    tags: ["hp", "adapter", "charger"],
    specifications: {
      SKU: "HP246EA3XM7MWNAFAMZ",
      "Weight (kg)": "0.5",
      Color: "Black",
    },
    variations: [
      {
        id: "16-bigpin",
        name: "Big Pin",
        price: 155000,
        originalPrice: 290000,
        stock: 3,
      },
      {
        id: "16-smallpin",
        name: "Small Pin",
        price: 165000,
        originalPrice: 290000,
        stock: 3,
      },
    ],
    mainFeatures: [
      "HP Laptop Charger 19.5V, 3.33A",
      "Charge and power your laptop with this Laptop Charger. This laptop power supply is engineered with enough power to deliver a strong charge to any compatible laptop. This unit gives you surge protection, over-current protection, voltage protection and over-temperature protection to keep your laptop operating and charging at the correct voltage",
      "Built to safeguard your laptop against damage, this charger will not let you down. Order for this Laptop charger from Jumia Kenya and have it delivered at your doorstep",
      "This unit gives you surge protection, over-current protection, voltage protection and over-temperature protection to keep your laptop operating and charging at the correct voltage. Built to safeguard your laptop against damage, this charger will not let you down",
    ],
    keyFeatures: [
      "Surge protection",
      "Over-current protection",
      "Voltage protection",
      "Over-temperature protection",
    ],
    whatsInTheBox: ["HP charger"],
    createdAt: "2024-01-06T13:30:00Z",
    updatedAt: "2024-01-16T15:45:00Z",
  },
  {
    id: "15",
    name: "Hp Refurbished EliteBook 820 Core I5 8GB RAM 500gb Hdd Slim Laptop",
    description:
      "Hp Refurbished EliteBook 820 Core I5 8GB RAM 500gb Hdd Slim Laptop - Black/sliver",
    price: 950000,
    originalPrice: 1350000,
    images: [
      "/computing/elitebook.jpg",
      "/computing/elitebook2.jpg",
      "/computing/elitebook3.jpg",
    ],
    category: "Computing",
    subcategory: "Laptops",
    brand: "Hp",
    stock: 7,
    rating: 4.6,
    reviewCount: 167,
    featured: true,
    tags: ["laptop", "hpelitebook", "hp", "elitebook"],
    specifications: {
      SKU: "HP246CL41RF0BNAFAMZ",
      "Weight (kg)": "1.9",
      Model: "820, 840",
      Certifications: "Eco Friendly",
      "Main Material": "PvC",
    },
    variations: [
      {
        id: "5-hp820",
        name: "Hp 820",
        price: 950000,
        originalPrice: 1350000,
        stock: 3,
      },
      {
        id: "5-hp840",
        name: "Hp 840",
        price: 1130000,
        originalPrice: 1550000,
        stock: 4,
      },
    ],
    mainFeatures: [
      "HP EliteBook 820 Laptop, Intel Core i5  8GB Ram, 5oogb HDD Drive, Windows 10 Pro 64bit Refurbished",
      "HP EliteBook 820 Windows 7 Professional  64-bit Edition / Windows 10 P",
      "When it comes to your family’s needs, the Refurbished HP 820 G1 has got everyone covered. Built with power and speed to tackle those to do lists. HP 820 G1 is a state of the art computer that offers top quality components to assure quality while performing both personal and business applications",
      "The HP EliteBook 820 G1 is a 12.5-inch business notebook, which belongs to the upper class among business devices. Overall, it left a good impression and does not need to hide from the competition",
      "Help get the most out of existing IT investments with legacy feature support available on the HP EliteBook 820 G1 like a DP port, a VGA port, and an RJ-45 connection",
      "Microsoft Windows 10 Pro 64 Language Supports English/Spanish/French is so familiar and easy to use, you’ll feel like an expert. It starts up and resumes fast, has more built-in security to help keep you safe, and comes with great built-in apps like Maps, Photos, Mail & Calendar, Music, and Video",
      "The HP EliteBook 820 G1 connects to the Internet using a high speed Gigabit Ethernet adapter or stable performance Wi-Fi",
    ],
    keyFeatures: [
      "Processor: Intel Core i5  2.1 GHz",
      "Hard disk size: 500GB HDD",
      "RAM Size: 8GB",
      "Connectivity type: Wi-Fi, Bluetooth",
      "Genuine HP EliteBook 820 Drivers Installed",
      "AC Adapter",
      "HP EliteBook 820 Laptop",
    ],
    whatsInTheBox: ["HP Elitebook 820", "Power Adaptor", "Flower Cable"],
    createdAt: "2024-01-05T16:45:00Z",
    updatedAt: "2024-01-21T12:00:00Z",
  },
  {
    id: "16",
    name: "Original Accessories Micro OTG Android Adapter",
    description: "Original Accessories Micro OTG Android Adapter - Silver",
    price: 20000,
    images: ["/computing/otg.jpg"],
    category: "Computing",
    subcategory: "Computer Accessories",
    brand: "Original Accessories",
    stock: 6,
    rating: 4.5,
    reviewCount: 98,
    featured: false,
    tags: ["otg", "usb", "mouse", "flash"],
    specifications: {
      SKU: "OR289EA3XE3M3NAFAMZ",
      "Weight (kg)": "0.1",
      Color: "Silver",
      "Main Material": "Plastic shell & Metal inside",
      "Connector A": "USB 3.1 Type C Male",
      "Connector B": "USB 3.0 Type A Female",
      Application: "Converting USB 3.1 port to standard USB port",
    },
    variations: [],
    mainFeatures: [
      "Plug and play,support two sides insert,easy for you Type c devices",
      "Supports external devices connect, like U disk, Fan, Keyboard, Mouse Camera Game Handle Microphone, Headset etc",
    ],
    keyFeatures: ["Micro OTG Android adapter-Silver"],
    whatsInTheBox: [],
    createdAt: "2024-01-04T11:20:00Z",
    updatedAt: "2024-01-14T13:40:00Z",
  },
  {
    id: "17",
    name: "AC 3 Pin Laptop Adapter Power Cord Cable with Fuse",
    description: "AC 3 Pin Laptop Adapter Power Cord Cable with Fuse - Black",
    price: 50000,
    images: ["/computing/powercord.jpg"],
    category: "Computing",
    subcategory: "Computer Accessories",
    brand: "Original Accessories",
    stock: 9,
    rating: 4.4,
    reviewCount: 203,
    featured: false,
    tags: ["cord", "powercable", "charging", "charger"],
    specifications: {
      SKU: "GE779EA40UEX7NAFAMZ",
      "Weight (kg)": "0.1",
    },
    variations: [],
    mainFeatures: [
      "Generic AC 3 Pin Laptop Notebook Adapter Power Cord Cable with Fuse - Black",
      "Replace your overused or misplaced power cable. This universal power cable is designed to work with most PCs, monitors, scanners, printers, projectors and musical/audio equipment",
      "C2G 0.5 Metre",
      "16 AWG cord, fully snagless design for maximum durability and long life",
      "Connector 1, BS 1363 Male UK 3 pin plug. Connector 2, C13 IEC",
      "Female Power Cable Connector. Also known as a kettle lead / kettle plug",
      "Fitted with a replaceable 13 Amp fuse, Outer Diameter 6.7mm +/- 0.2mm",
    ],
    keyFeatures: [
      "Enables you to position your PC as needed",
      "Equipped with a 13 A fuse",
      "It is durable with reliable performance",
      "Carries 250 V at 13A",
      "Durable",
    ],
    whatsInTheBox: [],
    createdAt: "2024-01-14T08:15:00Z",
    updatedAt: "2024-01-23T15:20:00Z",
  },
  {
    id: "18",
    name: "Toshiba TransMemory U202 64GB USB Flash Drive USB",
    description: "Toshiba TransMemory U202 64GB USB Flash Drive USB - White",
    price: 76000,
    originalPrice: 118300,
    images: ["/computing/flash.jpg"],
    category: "Computing",
    subcategory: "Computer Accessories",
    brand: "Toshiba",
    stock: 13,
    rating: 4.7,
    reviewCount: 167,
    featured: false,
    tags: ["flash", "disk", "memory"],
    specifications: {
      SKU: "TO006EA3LD56ZNAFAMZ",
      "Weight (kg)": "0.1",
    },
    variations: [],
    mainFeatures: [
      "Toshiba TransMemory U202 64GB USB Flash Drive USB 2.0 - White",
      "The USB 2.0 standard A Type has a size of 12mm width and a  height of 4.5mm. Suitable in all USB 2.0 ports which is standard in  every PC. Data transmission is possible in both directions",
      "This series is available in five different capacities from 8 to 128 GB. On the 32 GB USB drive (only available in white) you can store round about 11440 - 8 Megapixel photos, 8.000 songs or 32 hours of video",
      "Low power consumption is achieved thanks to Toshiba’s original technology, such as multi-layering of high-speed NAND flash memory and a dedicated low-power-consumption ASIC controller",
      "As a result, power consumption of notebook PCs is minimized even when using a USB flash memory",
      "These Flash drives are covered by a five year warranty from the date of purchase",
    ],
    keyFeatures: [
      "Storage: 64GB capacity Includes password protection security software",
      "Designed for everyday storage",
      "Small in size, big on storage",
      "5 Year Warranty",
    ],
    whatsInTheBox: [],
    createdAt: "2024-01-03T10:30:00Z",
    updatedAt: "2024-01-13T12:45:00Z",
  },
  {
    id: "19",
    name: "Other USB 3.0 High Speed Ethernet Network Adapter",
    description: "Other USB 3.0 High Speed Ethernet Network Adapter - Black",
    price: 95000,
    originalPrice: 180000,
    images: [
      "/computing/ethadapter.jpg",
      "/computing/ethadapter2.jpg",
      "/computing/ethadapter3.jpg",
    ],
    category: "Computing",
    subcategory: "Computer Accessories",
    brand: "Original Accessories",
    stock: 8,
    rating: 4.8,
    reviewCount: 234,
    featured: true,
    tags: ["usb", "ethernet", "adapter"],
    specifications: {
      SKU: "OT296EA3G1V9NNAFAMZ",
      "Weight (kg)": "0.3",
      Color: "Black",
      RAM: "Embedded 20KB SRAMD for RX packet buffering and 20KB SRAM for TX packet buffering",
    },
    variations: [],
    mainFeatures: [
      "Supports 10/100/1000 Mbps auto-sensing capability",
      "USB 3.0 Interface",
      "Backwards Compatible with USB 2.0",
      "Supports Auto MDIX (straight and cross network cable auto-detection)",
      "Supports USB full and high-speed modes with bus power capability",
      "IEEE 802.3, 802.3u, and 802.3ab (10Base-T, 100Base-TX, and 1000Base-T) compatible",
      "Supports both full-duplex and half-duplex operation in Fast Ethernet",
      "Supports Jumbo packet of up to 9KB",
      "Plug and Play Installation",
      "Support Windows 8, Windows 7, Windows Vista, Mac 10.6 and Later",
    ],
    keyFeatures: [
      "Support 10/100/1000 Mbps auto-sensing function",
      "USB 3.0 interface * Backward compatible with USB 2.0",
      "Support auto MDIX (straight and cross network cable automatic detection",
      "Support USS full speed and high-speed mode and bus power capability",
      "IEEE 802.3, 802.3u and 802.3ab (10 Base-T, 100Base-TX and 1000Base-T.) Compatible",
      "Support full-duplex and half-duplex operation of Fast Ethernet",
      "Support Jumbo packets up to 9 KB",
      "Supports suspend mode and remote wakeup via links and magic packs",
      "Plug and play installation",
    ],
    whatsInTheBox: [],
    createdAt: "2024-01-02T09:15:00Z",
    updatedAt: "2024-01-12T11:30:00Z",
  },
  {
    id: "20",
    name: "BVOT 4G USB Modem With Wi-Fi Hotspot 3 In 1",
    description: "BVOT 4G USB Modem With Wi-Fi Hotspot 3 In 1 - White",
    price: 130000,
    originalPrice: 250000,
    images: ["/computing/modem.jpg"],
    category: "Computing",
    subcategory: "Computer Accessories",
    brand: "bvot",
    stock: 12,
    rating: 4.5,
    reviewCount: 156,
    featured: false,
    tags: ["modem", "wifi", "4g"],
    specifications: {
      SKU: "GE779EA44VOHXNAFAMZ",
      "Weight (kg)": "0.75",
      Color: "Black, White",
    },
    variations: [],
    mainFeatures: [
      "Rate: down-link speed 100mbps / up-link speed 50mbps",
      "Free drive – inserting a sim card acts as a wireless router with simple operation – no need to set up",
      "Note: sim card and tf card not include, you will need to purchase this item separately",
      "Not only a 4g usb modem, but also a usb wi-fi router, users gain access to an ultra-speed internet connection with amazingly low power dissipation wireless access is available on both 3g/4g network and wi-fi networks",
    ],
    keyFeatures: [
      "High speed wireless connection up to 150Mbps",
      "Plug & Play – only power source required",
      "Internet sharing up to 10 Wi-Fi devices",
      "FDD/TDD-LTE, HSPA+HSPA",
      "4G/3G+Wi-Fi wireless access",
      "MicroSD card slot",
    ],
    whatsInTheBox: [],
    createdAt: "2024-01-01T15:45:00Z",
    updatedAt: "2024-01-11T17:20:00Z",
  },
  {
    id: "21",
    name: "D-Link 4G DWR-M960 1200Mbps LTE Simcard Router",
    description: "D-Link 4G DWR-M960 1200Mbps LTE Simcard Router - Black",
    price: 380000,
    originalPrice: 580000,
    images: [
      "/computing/dlink.jpg",
      "/computing/dlink2.jpg",
      "/computing/dlink3.jpg",
    ],
    category: "Computing",
    subcategory: "Computer Accessories",
    brand: "D-Link",
    stock: 12,
    rating: 4.9,
    reviewCount: 278,
    featured: true,
    tags: ["dlink", "router", "wifi", "internet"],
    specifications: {
      SKU: "DL723EA3U0P6TNAFAMZ",
      "Weight (kg)": "0.5",
      Color: "Black",
    },
    variations: [
      {
        id: "21-standard",
        name: "M960",
        price: 380000,
        originalPrice: 580000,
        stock: 12,
      },
    ],
    mainFeatures: [
      "D-Link DWR-M960 4G AC1200 LTE Router",
      "D-Link’s DWR-M960 4G AC1200 LTE Router allows you to access mobile broadband networks from anywhere. Once connected, you can check e-mail, surf the web, and stream media. Use your carrier’s SIM/UICC card to share your 3G/4G Internet connection through a secure wireless network or by using any of the four Gigabit ports",
      "The DWR-M960 lets you connect to your 3G/4G mobile connection with fast downlink speeds of up to 150 Mbps and uplink speeds up to 50 Mbps, giving you the speed you need for fast, responsive Internet access. Surf the web with ease and stream music and video over the Internet to your PCs and mobile devices",
      "Secure Wired and Wireless Connections",
      "The DWR-M960 utilizes dual-active firewalls (SPI and NAT) to prevent potential attacks across the Internet. Industry standard WPA/WPA2 wireless encryption keeps your wireless network secure and your traffic safe, allowing you to share your 3G/4G connection without worrying about unauthorized users accessing your network",
      "The DWR-M960 can be installed quickly and easily almost anywhere. It can be confi­gured through almost any web browser without the need for special software. This router makes it possible to stay connected, even when conventional broadband services are unavailable",
    ],
    keyFeatures: [
      "SIM card slot for a mobile broadband connection",
      "Four 10/100/1000 Ethernet LAN ports to connect, WAN port to connect to the Internet",
      "Supports WEP, WPA/WPA2 andWPA-PSK/WPA2-PSK encryption.Dual-active rewalls (NAT/SPI) to control tra c and prevent exploits and intrusions",
    ],
    whatsInTheBox: ["Router", "User Guide", "Adapter"],
    createdAt: "2023-12-30T14:20:00Z",
    updatedAt: "2024-01-10T16:35:00Z",
  },
  {
    id: "22",
    name: "Other Strap For Airpods Anti Lost Strap Rope",
    description: "Other Strap For Airpods Anti Lost Strap Rope - Black",
    price: 25000,
    originalPrice: 58000,
    images: [
      "/electronics/airpods.jpg",
      "/electronics/airpods2.jpg",
      "/electronics/airpods3.jpg",
      "/electronics/airpods4.jpg",
      "/electronics/airpods5.jpg",
      "/electronics/airpods6.jpg",
      "/electronics/airpods7.jpg",
    ],
    category: "Electronics",
    subcategory: "Accessories",
    brand: "Original Accessories",
    stock: 9,
    rating: 4.9,
    reviewCount: 278,
    featured: false,
    tags: ["airpods", "earpods", "earphones", "music"],
    specifications: {
      SKU: "OT296EA4Y6OSRNAFAMZ",
      "Product Line":
        "Cobcobb Air Strap Magnetic Cord Anti-Lost Leash Sports String Accessories for Bluetooth Earphone Pro/2/1 (3 Black)",
      "Weight (kg)": "0.01",
      Model: "Strap",
      Color: "Black",
      "Main Material": "Plastic",
    },
    variations: [],
    mainFeatures: [
      "Earbuds Strap Magnetic Cord Anti-Lost Leash Sports String Accessories for Bluetooth Airpods Pro/2/1",
      "High-Performance - our strap possesses a smooth finish, soft touch feeling, and excellent durability.Useful in Sports - Weightless-like (14gram), born for jogging, running, dancing, fitness, yoga, all sorts of vigorous sports and exercises",
      "Strong Magnetic & Safety. Built-in powerful magnets, offer strong magnetic continuously, hold and lock the Bluetooth Earphone around your neck tightly",
      "Ultra-light & flexible, light like air, premium silica gel provides better elasticity for the strap, soft and flexible",
      "Practical & worthy, enhance the stability of Airpods during exercises and sports, enjoy the fun of games freely. Reduce anxiety, eliminate the potential risk of dropping and lost, and the frequency of misplacing or backfill to the charging case",
      "Referring to reliable statistics: About 1/3 – 1/2 Airpods users had ever lost one earbud at least, and it’s cost bulk of the money to get a replacement. You may need an accessory for your Airpods to anti-lost. Our new generation of the magnetic strap is a great Protection",
    ],
    keyFeatures: [
      "Parameter: Length - 70cm (28inch) Weight – 14gram (0.026lb)",
      "Materials: Organic Silica",
      "Magnetic Earbuds strap",
      "Transparent resealable OPP bag x 1",
      "Safety Warning: Potential Chock Hazardous, Keep it away from children",
    ],
    whatsInTheBox: ["Neck strap"],
    createdAt: "2023-12-30T14:20:00Z",
    updatedAt: "2024-01-10T16:35:00Z",
  },
  {
    id: "23",
    name: "Sony 1.2v AA 4600Mah RECHARGEABLE BATTERIES",
    description: "Sony 1.2v AA 4600Mah RECHARGEABLE BATTERIES",
    price: 98000,
    originalPrice: 165000,
    images: ["/electronics/sonnyaa.jpg"],
    category: "Electronics",
    subcategory: "Accessories",
    brand: "Sonny",
    stock: 30,
    rating: 4.9,
    reviewCount: 278,
    featured: true,
    tags: ["sony", "aa", "dc", "battery"],
    specifications: {
      SKU: "SO521EA49H3L0NAFAMZ",
      "Weight (kg)": "0.9",
      Color: "White",
    },
    variations: [
      {
        id: "aa-standard",
        name: "AAA12345",
        price: 85000,
        originalPrice: 165000,
        stock: 12,
      },
      {
        id: "aaa-standard",
        name: "AAfudj",
        price: 98000,
        originalPrice: 165000,
        stock: 17,
      },
    ],
    mainFeatures: [
      "1.2v rechargeable cycle energy rechargeable battery made from improved Ni-MH",
      "This batteries can withstand working for long made from high quality",
      "Improved Ni-MH technology it's equipped with 4600Mah capacity",
      "This batteries are made from a reputable company that guarantees you of their fine quality",
    ],
    keyFeatures: ["High quality", "AA size", "4600Mah", "Powerful"],
    whatsInTheBox: ["1 pair sony rechargeable battery"],
    createdAt: "2023-12-30T14:20:00Z",
    updatedAt: "2024-01-10T16:35:00Z",
  },
  {
    id: "24",
    name: "Jangu Tech Mini Spy Secret Camera WiFi Wireless with Audio+32gb SD Card",
    description:
      "Jangu Tech Mini Spy Secret Camera WiFi Wireless with Audio+32gb SD Card - Black",
    price: 138000,
    originalPrice: 180000,
    images: [
      "/electronics/spycam.jpg",
      "/electronics/spycam2.jpg",
      "/electronics/spycam3.jpg",
      "/electronics/spycam4.jpg",
      "/electronics/spycam5.jpg",
      "/electronics/spycam6.jpg",
      "/electronics/spycam7.jpg",
      "/electronics/spycam8.jpg",
    ],
    category: "Electronics",
    subcategory: "Smart Home",
    brand: "Jangu Tech",
    stock: 7,
    rating: 4.9,
    reviewCount: 278,
    featured: true,
    tags: ["camera", "spy", "wifi", "security"],
    specifications: {
      SKU: "BR340EA3UH2QZNAFAMZ",
      "Product Line":
        "Mini Spy Camera, WiFi Wireless Tiny Secret Camera, Portable Home Security Hidden Camera with Audio and Video Live Feed for Indoor Outdoor",
      Model: "Mini Spy Secret Camera",
      "Weight (kg)": "0.2",
      Color: "Black",
    },
    variations: [],
    mainFeatures: [
      "2021 UPGRADED SPY CAMERA: A mini WiFi camera can support multiple users and one app can support multiple camerassimultaneously",
      "Just download the free App on your phone (Android, IOS) and configure it with router WIFI (Only 2.4GHz). Then you can view live video on the App remotely from anywhere in the world. Keep an eye on your home or office as a security spy camera.",
      "STREAMING: Wireless spy camera supports 1080P/ 720P HD Resolution Ratio to show a good performance in recording. Supports up to memory card. Full-time recording mode: Insert the microSD card, this secret camera will auto start 24/7 loop recording",
      "SUPER COMPACT HIDDEN CAMERA: The tiny covert camera designed for indoor/outdoor(size is 4.4*4.4*2.2cm). It’s smallest wifi spy camera and You can hide this mini camera at anywhere to record anything anytime and goes unnoticed. Perfect for used it as a nanny cam or a baby monitor with camera/body cam/home security camera/pet camera/mini video camera/portable camera for recording both capture photos and videos",
      "NIGHT VISION & BUILT-IN MAGNET: The small nanny camera built-in 6 hidden infrared LEDs enhances night vision for a clear display in low light condition(No-Glow in use). You can open night vision function through App. With internal magnet or magnetic bracket or magnetic tabs, you can attach this live streaming camera on any metal. Protect your home during the day and night perfectly. Please Note: there is no motion detector notification",
      "BUILT-IN BATTERY&HOTSPOT: this secret security camera can record video continuously about 50 mins with built-in battery. Also you can get the camera plugged into a USB charger (or power bank) for recording 24/7 hours. The spy camera built-in hotspots, so it can record without Wi-Fi too: just insert a SD card and turn on, the mini WiFi camera will auto record HD video files to sd card; It can also record videos even if the network is offline",
    ],
    keyFeatures: [
      "Hidden",
      "Office line record",
      "Live streaming",
      "Wifi record",
      "Night vision",
      "Built-in magnet",
      "Built-in battery",
    ],
    whatsInTheBox: [
      "Camera",
      "Charging Cable",
      "Memory card 32gb",
      "User Manual",
    ],
    createdAt: "2023-12-30T14:20:00Z",
    updatedAt: "2024-01-10T16:35:00Z",
  },
  {
    id: "25",
    name: "Global Star 17inch DVB-T2 HD Digital TV",
    description: "Global Star 17inch DVB-T2 HD Digital TV - Black",
    price: 250100,
    originalPrice: 550000,
    images: ["/electronics/globaltv.jpg", "/electronics/globaltv2.jpg"],
    category: "Electronics",
    subcategory: "Smart Home",
    brand: "Global Star",
    stock: 9,
    rating: 4.9,
    reviewCount: 278,
    featured: true,
    tags: ["tv", "global", "smarthome"],
    specifications: {
      SKU: "GL325EA4NJ12JNAFAMZ",
      "Product Line": "All Ages",
      Model: "17",
      "Size (L x W x H cm)": "1920 x 1080",
      "Weight (kg)": "5.55",
      Color: "Black",
    },
    variations: [],
    mainFeatures: [
      "Globalstar – 17″ DVB-T2 HD Digital TV – Black",
      "The 17″ backlit LED panel of the television produces eye catching",
      "HD resolution images that are simply stunning to look at. This TV also has a number of ports to keep you well connected at all times, and these include the USB and HDMI ports",
      "Available exclusively at Dombelo Uganda, order for this Digital HDTV at an unbeatable price and let us deliver straight to your doorstep",
      "The globalstar 17 inch HD LED TV’s makes a perfect addition to contemporary rooms. When switched on, the backlit LED screen churns out images and videos with amazing contrast and details",
      "The globalstar 17″ HD LED display generates amazingly clear, razor sharp images with a resolution of 720p HD. More over, it comes with the latest DVB-T2 technology for the best & clearest analog TV signals so you can enjoy in-built free local TV channels off the box",
      "Witness the entire RCG spectrum brought to life on your screen. The Wegastar  LED TV brings you exceptionally vibrant and true-to-life images delivered just as the director imagined",
      "Provides you the flexibility to enjoy not only photos or music, but also HD multimedia files directly in your TV via USB",
      "Explorer More Connectivity Options",
      "The TV features 2 USB ports, and 2 HDMI ports to which you can connect your DVD players, cameras, external hard drives, and more. Now you can enjoy all your multimedia content of these gadgets on the big screen, right from the comfort of your couch. It also features a VGA & PC audio input",
    ],
    keyFeatures: [
      "Digital TV",
      "Screen Size (Inch): 17 inch",
      "Digital DVB-T2 ready",
      "Narrow Frame",
      "Eco-Friendly",
      "Resolution: 1920 x 1080 Pixels",
      "Connectivity: USB/HDMI/VGA",
      "USB port – Enjoy photos, music, and video right on the screen",
      "Free channels",
    ],
    whatsInTheBox: ["TV", "Manual", "Remote included"],
    createdAt: "2023-12-30T14:20:00Z",
    updatedAt: "2024-01-10T16:35:00Z",
  },
  {
    id: "26",
    name: "Multipurpose Tripod 18inch Remote Control LED Ring Light With 3 Cell Phone Holders And A Free Tripod Stand",
    description:
      "Multipurpose Tripod 18inch Remote Control LED Ring Light With 3 Cell Phone Holders And A Free Tripod Stand - Black, White",
    price: 255000,
    originalPrice: 670000,
    images: [
      "/electronics/tripod.jpg",
      "/electronics/tripod2.jpg",
      "/electronics/tripod3.jpg",
      "/electronics/tripod4.jpg",
    ],
    category: "Electronics",
    subcategory: "Smart Home",
    brand: "Multipurpose Tripod",
    stock: 10,
    rating: 4.9,
    reviewCount: 278,
    featured: true,
    tags: ["tripod", "content", "light", "recording"],
    specifications: {
      SKU: "MU766EA45O0X7NAFAMZ",
      "Product Line": "Tripod stand, Multi Tripod stand",
      Model: "Tripod",
      "Weight (kg)": "0.004",
      Color: "Black, White",
      "Main Material": "Plastic",
    },
    variations: [],
    mainFeatures: [
      "A Brighter View. This ring light will satisfy all your requirement in different circumstances.When taking selfies, you can choose different lights according to the needs of the scene to create a more colorful selfie effect. Compare to the flat lampshade, the upgraded arched lamp shade can reduce the irritation of light and protect our eyes",
      "Upgraded Tripod Stand.The newest adjustable tripod stand made of high-quality aluminum, using a more stable structure. It can be adjusted to any length and extended according to your requirement. Not easy to fall out and can be used as a cellphone holder and rotate to the angle you want.With non-slip rubber to hold your phone firmly without scratching it",
      "Widely Application.This selfie ring light is a perfect partner for our life and work, and the led camera selfie light ring has multi-usage, such as popular Tik Tok small video, live streaming, vlogging, selfie photos, makeup. Perfect for all kinds of close-up photography and filming. Such as fashion, advertisement, portrait, wedding",
      "USB Powered.No battery needed, works with most devices that support USB port, like a laptop, power bank, USB charger, AC adapter and etc. Wireless remote that is convenient for you to take photos or selfie with your friends or family, it is compatible with the android and iOS system so it doesn’t matter what phone you are using",
    ],
    keyFeatures: [
      "This ring light is made of 80pcs SMD LED,10W",
      "Light Color - white, warm yellow, soft light (warm yellow + white)",
      "Built-in high-quality SMD LED lights",
      "Compatible for all smartphones",
    ],
    whatsInTheBox: [
      "Ring Light",
      "Tripod stand",
      "Phone holders",
      "Remote Control",
    ],
    createdAt: "2023-12-30T14:20:00Z",
    updatedAt: "2024-01-10T16:35:00Z",
  },
  {
    id: "27",
    name: "Apple Airpods 3 (3rd Generation)-White",
    description: "Apple Airpods 3 (3rd Generation) - White",
    price: 895000,
    originalPrice: 1088000,
    images: [
      "/electronics/earpods.jpg",
      "/electronics/earpods2.jpg",
      "/electronics/earpods3.jpg",
      "/electronics/earpods4.jpg",
      "/electronics/earpods5.jpg",
    ],
    category: "Electronics",
    subcategory: "Accessories",
    brand: "Apple",
    stock: 10,
    rating: 4.9,
    reviewCount: 278,
    featured: true,
    tags: ["pods", "airpods", "earpods", "music"],
    specifications: {
      SKU: "AP044EA3RBH8RNAFAMZ",
      "Product Line": "Audio Devices",
      Model: "Airpods 3 (3rd Generation)",
      "Weight (kg)": "0.5",
      Color: "White",
    },
    variations: [],
    mainFeatures: [
      "Patial audio with dynamic head tracking places sound all around youAdaptive EQ automatically tunes music to your ears",
      "All-new contoured design",
      "Force sensor lets you easily control your entertainment, answer or end calls, and more",
      "Sweat and water resistantUp to 6 hours of listening time with one charge",
      "Up to 30 hours total listening time with the MagSafe Charging Case",
      "Quick access to Siri by saying “Hey Siri”",
      "Effortless setup, in-ear detection, and automatic switching for a magical experience",
      "Easily share audio between two sets of AirPods on your iPhone, iPad, iPod touch, or Apple TV",
    ],
    keyFeatures: [
      "Brand-Apple",
      "Ear Placement-In Ear",
      "Connectivity Technology-Wireless, Apple H1 Chip",
      "Model Name-AirPods",
    ],
    whatsInTheBox: ["1 x Air pods", "1 x Charger"],
    createdAt: "2023-12-30T14:20:00Z",
    updatedAt: "2024-01-10T16:35:00Z",
  },
  {
    id: "28",
    name: "JBL CLIP 4 - Portable Bluetooth Waterproof Speaker",
    description: "JBL CLIP 4 - Portable Bluetooth Waterproof Speaker - Black",
    price: 295100,
    originalPrice: 450000,
    images: [
      "/electronics/jbl.jpg",
      "/electronics/jbl2.jpg",
      "/electronics/jbl3.jpg",
      "/electronics/jbl4.jpg",
    ],
    category: "Electronics",
    subcategory: "Smart Home",
    brand: "JBL",
    stock: 9,
    rating: 4.9,
    reviewCount: 278,
    featured: true,
    tags: ["jbl", "speaker", "robot", "music"],
    specifications: {
      SKU: "JB812EA3OMNWJNAFAMZ",
      "Product Line": "All age products",
      Model: "Clip 4",
      "Weight (kg)": "0.527",
      Color: "Black",
    },
    variations: [],
    mainFeatures: [
      "Bring the party nearly anywhere you go with the black  Clip 4 Portable Bluetooth Speaker. With a built-in carabiner and rechargeable battery that lasts up to 10 hours, you can clip the speaker to your bag, belt loop, or whatever else is handy and stream music, podcasts, and more wirelessly via Bluetooth as you travel",
      "Its IP67 rating means it's waterproof and dustproof, so it's safe at the beach or poolside, even if it rains or gets splashed. It outputs up to 5W from its 1.5 inch driver",
      "The Clip 4 features a portable design with a built-in carabiner, so you can clip it to your belt, bag strap, or buckle, and take it nearly anywhere. It's engineered to deliver rich audio and punchy bass, despite its compact size",
      "The Clip 4 is IP67 rated to be waterproof and dustproof, so you can bring it to the pool, park, or wherever",
      "Stream music wirelessly from your phone, tablet, or any other compatible Bluetooth-enabled device",
      "With up to 10 hours of battery life on a single charge, you can play music without worrying about recharging",
      "Oval shape designed to fit easily into your hand",
      "Fully wrapped in fabric",
      "3-hour charge time",
    ],
    keyFeatures: [
      "Transducer: 40mm / 1.5inches",
      "Output power: 5W RMS",
      "Frequency response: 100Hz - 20kHz",
      "Signal-to-noise ratio: 85dB",
      "Type: -ion polymer 3.885Wh",
      "Charge time: 3 hours (5V/500mA)",
      "Music playtime: up to 10 hours (varies by volume level and audio content)",
      "Bluetooth version: 5.1",
      "Bluetooth profile: A2DP 1.3, AVRCP 1.6",
      "Bluetooth transmitter power: 10 dBm (EIRP)",
      "Bluetooth transmitter modulation: GFSK, /4 DQPSK, 8DPSK",
      "Dimensions (W x H x D): 3.4inches x 5.3inches x 1.8inches",
      "Weight: 0.527 lbs",
    ],
    whatsInTheBox: [
      "JBL Clip 4",
      "Type C USB cable",
      "Quick start guide",
      "Warranty card",
      "Saftey sheet",
    ],
    createdAt: "2023-12-30T14:20:00Z",
    updatedAt: "2024-01-10T16:35:00Z",
  },
  {
    id: "29",
    name: "Apple Earphone Wired Lightining Earphone Built-in Mic & Volume Control Compatible with iPhone 14/13/12/11 Pro Max Xs/XR/X/7/8 Plus-All iOS",
    description:
      "Apple Earphone Wired Lightining Earphone Built-in Mic & Volume Control Compatible with iPhone 14/13/12/11 Pro Max Xs/XR/X/7/8 Plus-All iOS",
    price: 150000,
    originalPrice: 230000,
    images: [
      "/electronics/applepods.jpg",
      "/electronics/applepods2.jpg",
      "/electronics/applepods3.jpg",
      "/electronics/applepods4.jpg",
      "/electronics/applepods5.jpg",
      "/electronics/applepods6.jpg",
    ],
    category: "Electronics",
    subcategory: "Accessories",
    brand: "Apple",
    stock: 9,
    rating: 4.9,
    reviewCount: 278,
    featured: true,
    tags: ["apple", "earphones", "airpods", "music"],
    specifications: {
      SKU: "AP044EA4ITJP3NAFAMZ",
      Model: "Apple",
      "Weight (kg)": "0.1",
      Color: "White",
      "Main Material": "Rubber",
      "Warranty Address": "Shop",
    },
    variations: [],
    mainFeatures: [
      "Say goodbye to the complexities of Bluetooth pairing. These headphones are equipped with an MFi-certified chip, making them plug-and-play ready. Simply connect the earbuds to your device, and you're good to go",
      "Designed to work seamlessly with a wide range of Apple products, such as iPhone 14/14 Pro/14 Pro Max/13/13 Pro/13 Pro Max/12/12 Pro/12 Pro Max/11/11 Pro/11 Pro Max/iPhone X/XS/XS Max/XR, iPhone 8 & 8 Plus/7 & 7 Plus and supports all iOS systems",
      "These in-ear headphones deliver crystal-clear studio-grade performance, featuring powerful bass, well-defined mid-range, and precise treble responses, ensuring exceptional audio quality, allowing you to savor high-definition music",
      "With the built-in remote and microphone, you can easily adjust the volume, manage playback, and answer or end calls with a simple pinch of the cord. The speakers inside the earphones optimize sound output while minimizing sound loss",
      "Every component, from the speakers and buttons to the headphone cable and connection port, is crafted from high-quality materials, guaranteeing durability, resistance to damage, and exceptional value for your investment",
    ],
    keyFeatures: [
      "Simplified Plug & Play",
      "Unmatched Compatibility",
      "Superior Audio Experience",
      "Effortless Control and Communication",
      "Premium Build and Durability",
    ],
    whatsInTheBox: ["Earphones.", "User Manual"],
    createdAt: "2023-12-30T14:20:00Z",
    updatedAt: "2024-01-10T16:35:00Z",
  },
  {
    id: "30",
    name: "Djack Bluetooth, FM, SD Card, USB Home Theatre DJ-903L - Black",
    description:
      "Djack Bluetooth, FM, SD Card, USB Home Theatre DJ-903L - Black",
    price: 245000,
    originalPrice: 350100,
    images: ["/electronics/djack.jpg"],
    category: "Electronics",
    subcategory: "Smart Home",
    brand: "Djack",
    stock: 13,
    rating: 4.9,
    reviewCount: 278,
    featured: true,
    tags: ["speaker", "music", "djack"],
    specifications: {
      SKU: "DJ561EA42MPQJNAFAMZ",
      "Weight (kg)": "15",
      Color: "Black",
    },
    variations: [],
    mainFeatures: [
      "DJACK 903L Bluetooth, FM, SD Card, USB Home Theatre - Black",
      "The 3.1 x-bass bluetooth home theatre system DJ-903L Home Theater is manufactured by Djack. This version of the Home Theater  comes in Refresh Rate : 38 HZ.",
    ],
    keyFeatures: [
      "Brand Name: DJACK",
      "Channels: 33",
      "Player Type: Other",
      "Package: Colored Box",
      "Function: Bluetooth",
      "Support: FM/USB/SD Iput/USB/SD/MMC/DVD/PC/MP3/Mobile Phone",
    ],
    whatsInTheBox: [],
    createdAt: "2023-12-30T14:20:00Z",
    updatedAt: "2024-01-10T16:35:00Z",
  },
  {
    id: "31",
    name: "Phelistar Free To Air Decoder DVB T2 TERRESTRIAL PH-9008 - Black",
    description:
      "Phelistar Free To Air Decoder DVB T2 TERRESTRIAL PH-9008 - Black",
    price: 60000,
    originalPrice: 75000,
    images: ["/electronics/freetoair.jpg"],
    category: "Electronics",
    subcategory: "Smart Home",
    brand: "GoTV",
    stock: 13,
    rating: 4.9,
    reviewCount: 278,
    featured: true,
    tags: ["freetoair", "phelister", "gotv"],
    specifications: {
      SKU: "GE779EA438B5HNAFAMZ",
      "Weight (kg)": "0.75",
      Color: "Black",
    },
    variations: [],
    mainFeatures: [
      "Front panel: The panel has power button, channel down, channel up which can be used for selecting channels to the user",
      "Rear panel: This panel has the RF IN, the socket the socket that connects to your external Aerial",
      "RF LOOP THROUGH; This socket will feed the RF Signal to either your TV or another video system, it also supports coaxial, video/audio output plus the HDMI for high definition audio and video output used to connect a HDMI device",
      "Remote control: It posses buttons like Power, Menu, Numeric keys, OK, Volume down, Volume up Language, Exit that allow the user to select to any options of his choice",
    ],
    keyFeatures: [
      "Power button",
      "Channel up",
      "Channel down",
      "LED display screen",
      "Remote Control Sensor",
      "USB support",
    ],
    whatsInTheBox: [],
    createdAt: "2023-12-30T14:20:00Z",
    updatedAt: "2024-01-10T16:35:00Z",
  },
  {
    id: "32",
    name: "Sollatek Wall Mount for 14 inches - 42 inches LED/LCD/Plasma TV - Black + TV Guard",
    description:
      "Sollatek Wall Mount for 14 inches - 42 inches LED/LCD/Plasma TV - Black + TV Guard",
    price: 43300,
    originalPrice: 85100,
    images: ["/electronics/wallmountguard.jpg"],
    category: "Electronics",
    subcategory: "Smart Home",
    brand: "Sollatech",
    stock: 7,
    rating: 4.9,
    reviewCount: 278,
    featured: true,
    tags: ["wallmount", "tvstand", "fridgeguard"],
    specifications: {
      SKU: "SO229EA3ETDJFNAFAMZ",
      Model: "OVU748",
      "Weight (kg)": "2",
      Color: "Black",
      "Main Material": "Aluminium",
    },
    variations: [],
    mainFeatures: [
      "Fits for most of Samsung/ hisense/ LG/ Sharp/ Sony / Toshiba/ Seiki/ Panasonic/ NEC/ TCL/ Philips/ Haier",
      "Loading weight capacity: max55lbs (25kg)",
      "Compatible screen size: 14 '' - 42 inches",
      "Built-in safety lock keeps your flat panel TV safe and stable",
      "Perfect positioning is guaranteed by removable bubble level",
      "Universal hole pattern",
    ],
    keyFeatures: [
      "Loading weight capacity: max55lbs (25kg)",
      "Universal hole pattern",
      "Built-in safety lock keeps your flat panel TV safe and stable",
      "Perfect positioning is guaranteed by removable bubble level",
    ],
    whatsInTheBox: ["Tv wall mount 14-42 inches", "Tv guard"],
    createdAt: "2023-12-30T14:20:00Z",
    updatedAt: "2024-01-10T16:35:00Z",
  },
  {
    id: "33",
    name: "Sollatek 13Amps Fridge Guard - White",
    description: "Sollatek 13Amps Fridge Guard - White",
    price: 38000,
    originalPrice: 50100,
    images: ["/electronics/guard.jpg"],
    category: "Electronics",
    subcategory: "Smart Home",
    brand: "Sollatech",
    stock: 5,
    rating: 4.9,
    reviewCount: 278,
    featured: true,
    tags: ["guard", "fridgeguard"],
    specifications: {
      SKU: "SO229EA4CR30RNAFAMZ",
      "Weight (kg)": "0.5",
    },
    variations: [],
    mainFeatures: [
      "Generic Fridge Guard secures your refrigerator, fridge, and freezer from sudden spikes and fluctuation from the main power supply or generator",
      "The device comes with features that keep in check any low power that is under-voltage and can damage your electrical appliances",
      "It protects your appliance by disconnecting the power when it goes below an unacceptable level that might damage the compressor",
      "The delay function keeps the fridge in control till the power returns to normal and this ensures that the appliance is not switched on-off repeatedly during fluctuations",
      "Having the fridge guard for your cooling appliances is essential as the massive surge from the main power supply or generator is control till it becomes normal",
    ],
    keyFeatures: [
      "Nominal Voltage: 230V",
      "Current Rating: 5Amps",
      "Frequency: 50/60Hz",
      "Under-Voltage Disconnect: 185V",
      "Under-Voltage Reconnect: 190V",
    ],
    whatsInTheBox: [],
    createdAt: "2023-12-30T14:20:00Z",
    updatedAt: "2024-01-10T16:35:00Z",
  },
];

export const banners: Banner[] = [
  {
    id: "1",
    title: "New Year Sale",
    subtitle: "Up to 50% off on selected items",
    image: "/new-year-sale-banner.jpg",
    link: "/promotions/new-year-sale",
    buttonText: "Shop Now",
    active: true,
    order: 1,
  },
  {
    id: "2",
    title: "Latest Electronics",
    subtitle: "Discover cutting-edge technology",
    image: "/electronics-banner.png",
    link: "/categories/electronics",
    buttonText: "Explore",
    active: true,
    order: 2,
  },
  {
    id: "3",
    title: "Fashion Forward",
    subtitle: "Trending styles for every season",
    image: "/fashion-banner.png",
    link: "/categories/fashion",
    buttonText: "Shop Fashion",
    active: true,
    order: 3,
  },
];

export const promotions: Promotion[] = [
  {
    id: "1",
    title: "New Year Mega Sale",
    description: "Get up to 50% off on electronics and fashion items",
    discountType: "percentage",
    discountValue: 50,
    code: "NEWYEAR50",
    startDate: "2024-01-01T00:00:00Z",
    endDate: "2024-01-31T23:59:59Z",
    active: true,
    applicableCategories: ["Phones and Tablets", "Computers", "Fashion"],
  },
  {
    id: "2",
    title: "Free Shipping Weekend",
    description: "Free shipping on all orders above Ugx 20,000",
    discountType: "fixed",
    discountValue: 0,
    startDate: "2024-01-26T00:00:00Z",
    endDate: "2024-01-28T23:59:59Z",
    active: true,
  },
];

export const reviews: Review[] = [
  {
    id: "1",
    productId: "1",
    customerName: "John Smith",
    customerEmail: "john@example.com",
    rating: 5,
    title: "Amazing phone!",
    comment:
      "The iPhone 15 Pro Max exceeded my expectations. The camera quality is incredible and the battery life is outstanding.",
    verified: true,
    helpful: 12,
    createdAt: "2024-01-20T14:30:00Z",
  },
  {
    id: "2",
    productId: "2",
    customerName: "Sarah Johnson",
    customerEmail: "sarah@example.com",
    rating: 5,
    title: "Perfect for work",
    comment:
      "This MacBook Pro handles all my design work effortlessly. The display is stunning and performance is top-notch.",
    verified: true,
    helpful: 8,
    createdAt: "2024-01-18T16:45:00Z",
  },
  {
    id: "3",
    productId: "3",
    customerName: "Mike Davis",
    customerEmail: "mike@example.com",
    rating: 4,
    title: "Great noise cancellation",
    comment:
      "These headphones are fantastic for travel. The noise cancellation works really well on flights.",
    verified: true,
    helpful: 15,
    createdAt: "2024-01-22T13:15:00Z",
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "1",
    customerName: "Emily Chen",
    customerImage: "/customer-profile-woman.jpg",
    rating: 5,
    comment:
      "Excellent service and fast delivery. The products are exactly as described and the quality is outstanding.",
    location: "New York, NY",
    verified: true,
    featured: true,
    createdAt: "2024-01-15T10:00:00Z",
  },
  {
    id: "2",
    customerName: "David Wilson",
    customerImage: "/customer-profile-man.jpg",
    rating: 5,
    comment:
      "I've been shopping here for months and never had a bad experience. Great customer support and competitive prices.",
    location: "Los Angeles, CA",
    verified: true,
    featured: true,
    createdAt: "2024-01-12T11:30:00Z",
  },
  {
    id: "3",
    customerName: "Lisa Rodriguez",
    customerImage: "/customer-profile-woman-hispanic.jpg",
    rating: 5,
    comment:
      "The website is easy to navigate and the checkout process is smooth. Highly recommend this store!",
    location: "Miami, FL",
    verified: true,
    featured: true,
    createdAt: "2024-01-10T09:00:00Z",
  },
];
